version: '3.7'

services:
  mq:
    image: "rabbitmq:3.8-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_HEARTBEAT: 30
    ports:
      - target: 15672
        published: 15672
        mode: host
      - target: 5672
        published: 5672
        mode: host
    volumes:
      - data:/var/lib/rabbitmq
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.rabbit == master
      resources:
        limits:
          cpus: '4'
          memory: 6G

volumes:
  data:
    driver: local

networks:
  backend:
    external: true
