version: '3.7'

services:
  mq:
    image: "rabbitmq:3.8-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_HEARTBEAT: 30
    ports:
      - "15671-15672"
      - "5671-5672"
    volumes:
      - data:/var/lib/rabbitmq
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.rabbit == master

volumes:
  data:
    driver: local
